export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const SET_EDITING_USER = 'SET_EDITING_USER';
export const CLEAR_EDITING_USER = 'CLEAR_EDITING_USER';
export const SET_FILTER = 'SET_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const TOGGLE_MENU = 'TOGGLE_MENU';
